language: csharp
solution: TensorFlowSharp.sln
mono:
  - latest
install:
  - nuget restore TensorFlowSharp.sln
script:
  - xbuild /p:Configuration=Release TensorFlowSharp.sln
  - sh $TRAVIS_BUILD_DIR/build.sh