language: csharp
solution: TensorFlowSharp.sln
mono:
  - latest
install:
  - nuget restore TensorFlowSharp.sln
script:
  - xbuild /p:Configuration=Release TensorFlowSharp.sln
before_script: cd tests/TensorFlowSharp.Tests/bin/Release
script:
  - mono xunit.console.exe TensorFlowSharp.Tests.dll xunit.console.exe.config