language: csharp
solution: TensorFlowSharp.sln

  - nuget restore $TRAVIS_BUILD_DIR/TensorFlowSharp.sln
  - xbuild /p:Configuration=Release TensorFlowSharp.sln
  - sh $TRAVIS_BUILD_DIR/build.sh
mono: "none"
os: "osx"