language: csharp
solution: TensorFlowSharp.sln
mono:
  - latest
install:
  - nuget restore TensorFlowSharp.sln
script:
  - xbuild /p:Configuration=Release TensorFlowSharp.sln
  - mono ./tests/TensorFlowSharp.Tests/bin/Release/xunit.console.exe ./tests/TensorFlowSharp.Tests/bin/Release/TensorFlowSharp.Tests.dll ./tests/TensorFlowSharp.Tests/bin/Release/xunit.console.exe.config