language: csharp
solution: TensorFlowSharp.sln
script:
  - tsh_version=1.4.0-pre1
  - tests_output_path=$TRAVIS_BUILD_DIR/tests/TensorFlowSharp.Tests/bin/Release/netstandard2.0
  - cstests_output_path=$TRAVIS_BUILD_DIR/tests/TensorFlowSharp.Tests.CSharp/bin/Release/netstandard2.0

  - wget "https://www.nuget.org/api/v2/package/TensorFlowSharp/$tsh_version"
  - tar xzvf $tsh_version native
  - msbuild /t:Restore $TRAVIS_BUILD_DIR/TensorFlowSharp.sln
  - cd $TRAVIS_BUILD_DIR/
  - msbuild /p:Configuration=Release TensorFlowSharp.sln
  - cp -R $TRAVIS_BUILD_DIR/native/*.dylib $tests_output_path
  - cp -R $TRAVIS_BUILD_DIR/native/*.dylib $cstests_output_path
  - cd tests\TensorFlowSharp.Tests.CSharp
  - dotnet xunit -c Release
mono: "5.4.1"
dotnet: "2.0.0"
os: "osx"
