language: csharp
solution: TensorFlowSharp.sln
mono:
  - latest
install:
  - nuget restore TensorFlowSharp.sln
  - nuget install xunit.runners -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TensorFlowSharp.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./tests/TensorFlowSharp.Tests/bin/Release/TensorFlowSharp.Tests.dll